spring:
  main:
    headless: false
  application:
    name: av-car-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:avcar}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jackson:
    date-format: ${JACKSON_DATE_FORMAT:yyyy-MM-dd}
    time-zone: ${JACKSON_TIME_ZONE:America/Sao_Paulo}

server:
  port: ${SERVER_PORT:8080}

springdotenv:
  directory: ../av_car_infra
  filename: .env
  ignoreIfMissing: true

springdoc:
  swagger-ui:
    url: http://localhost:8080/swagger-ui/index.html