/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.senai.fatesg.avcar.swing.views;

/**
 *
 * @author lucio-aguiar
 */
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;

import br.edu.senai.fatesg.avcar.swing.views.presenters.CadastroFilaDeEsperaPresenter;

@Component
public class CadastroFilaDeEspera extends javax.swing.JPanel {

    private final CadastroFilaDeEsperaPresenter presenter;

    @Autowired
    public CadastroFilaDeEspera(CadastroFilaDeEsperaPresenter presenter) {
        this.presenter = presenter;
        initComponents();
    }

    @jakarta.annotation.PostConstruct
    public void initLogic() {
        presenter.initLogic(this);
    }

    public void carregarDados() {
        presenter.carregarDados(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumOS = new javax.swing.JLabel();
        jButtonAddNumOSPrioridade = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaidaFilaAtend = new javax.swing.JTextArea();
        jToggleButtonRemoverFila = new javax.swing.JToggleButton();
        jButtonProxFila = new javax.swing.JButton();
        jButtonLimparFila = new javax.swing.JButton();
        jButtonFecharFilaAtend = new javax.swing.JButton();
        jComboBoxOSFila = new javax.swing.JComboBox<>();

        jLabelNumOS.setText("OS");

        jButtonAddNumOSPrioridade.setText("Add Fila");

        jTextAreaSaidaFilaAtend.setColumns(20);
        jTextAreaSaidaFilaAtend.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaidaFilaAtend);

        jToggleButtonRemoverFila.setText("Remover");

        jButtonProxFila.setText("Proximo da Fila");

        jButtonLimparFila.setText("Limpar tudo");

        jButtonFecharFilaAtend.setText("Fechar");



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelNumOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxOSFila, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddNumOSPrioridade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonRemoverFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProxFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimparFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFecharFilaAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumOS)
                    .addComponent(jButtonAddNumOSPrioridade)
                    .addComponent(jComboBoxOSFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonRemoverFila)
                    .addComponent(jButtonProxFila)
                    .addComponent(jButtonLimparFila)
                    .addComponent(jButtonFecharFilaAtend))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNumOSPrioridade;
    private javax.swing.JButton jButtonFecharFilaAtend;
    private javax.swing.JButton jButtonLimparFila;
    private javax.swing.JButton jButtonProxFila;
    private javax.swing.JComboBox<br.edu.senai.fatesg.avcar.business.ordemservico.OrdemServicoDTO> jComboBoxOSFila;
    private javax.swing.JLabel jLabelNumOS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaidaFilaAtend;
    private javax.swing.JToggleButton jToggleButtonRemoverFila;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getButtonAddNumOSPrioridade() { return jButtonAddNumOSPrioridade; }
    public javax.swing.JButton getButtonFecharFilaAtend() { return jButtonFecharFilaAtend; }
    public javax.swing.JButton getButtonLimparFila() { return jButtonLimparFila; }
    public javax.swing.JButton getButtonProxFila() { return jButtonProxFila; }
    public javax.swing.JComboBox<br.edu.senai.fatesg.avcar.business.ordemservico.OrdemServicoDTO> getComboBoxOSFila() { return jComboBoxOSFila; }
    public javax.swing.JLabel getLabelNumOS() { return jLabelNumOS; }
    public javax.swing.JTextArea getTextAreaSaidaFilaAtend() { return jTextAreaSaidaFilaAtend; }
    public javax.swing.JToggleButton getToggleButtonRemoverFila() { return jToggleButtonRemoverFila; }
}
