package br.edu.senai.fatesg.avcar.swing.views;

import br.edu.senai.fatesg.avcar.business.ordemservico.OrdemServicoController;
import br.edu.senai.fatesg.avcar.business.veiculos.VeiculoController;
import br.edu.senai.fatesg.avcar.business.veiculos.VeiculoDTO;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.ArrayList;

import br.edu.senai.fatesg.avcar.swing.views.presenters.CadastroOSPresenter;

@Component
public class CadastroOS extends javax.swing.JPanel {

    private final CadastroOSPresenter presenter;

    @Autowired
    public CadastroOS(CadastroOSPresenter presenter) {
        this.presenter = presenter;
        initComponents();
    }
    
    @jakarta.annotation.PostConstruct
    public void initLogic() {
        presenter.initLogic(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroOS = new javax.swing.JPanel();
        jLabelVeiculoCadatroOS = new javax.swing.JLabel();
        jLabelDataEntradaCadastroOS = new javax.swing.JLabel();
        jButtonSalvarCadastroOS = new javax.swing.JButton();
        jButtonCancelarCadastroOS = new javax.swing.JButton();
        jComboBoxVeiculoCadastroOS = new javax.swing.JComboBox<>();
        jFormattedTextFieldDataEntradaCadastroOS = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanelDefeitoRelatadoCadastroOS = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDefeitoRelatadoCadastroOS = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxResponsavelCadastroOS = new javax.swing.JComboBox<>();

        setToolTipText("Novo Cliente");

        jPanelCadastroOS.setToolTipText("Insira os Dados do novo Cliente");

        jLabelVeiculoCadatroOS.setText("Veículo:");

        jLabelDataEntradaCadastroOS.setText("Data Entrada:");

        jButtonSalvarCadastroOS.setText("Salvar");
        jButtonSalvarCadastroOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadastroOSActionPerformed(evt);
            }
        });

        jButtonCancelarCadastroOS.setText("Cancelar");
        jButtonCancelarCadastroOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCadastroOSActionPerformed(evt);
            }
        });

        jComboBoxVeiculoCadastroOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanelDefeitoRelatadoCadastroOS.setBorder(javax.swing.BorderFactory.createTitledBorder("Defito Relatado"));

        jTextAreaDefeitoRelatadoCadastroOS.setColumns(20);
        jTextAreaDefeitoRelatadoCadastroOS.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDefeitoRelatadoCadastroOS);

        javax.swing.GroupLayout jPanelDefeitoRelatadoCadastroOSLayout = new javax.swing.GroupLayout(jPanelDefeitoRelatadoCadastroOS);
        jPanelDefeitoRelatadoCadastroOS.setLayout(jPanelDefeitoRelatadoCadastroOSLayout);
        jPanelDefeitoRelatadoCadastroOSLayout.setHorizontalGroup(
            jPanelDefeitoRelatadoCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefeitoRelatadoCadastroOSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelDefeitoRelatadoCadastroOSLayout.setVerticalGroup(
            jPanelDefeitoRelatadoCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefeitoRelatadoCadastroOSLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDefeitoRelatadoCadastroOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDefeitoRelatadoCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("Atendente:");

        jComboBoxResponsavelCadastroOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelCadastroOSLayout = new javax.swing.GroupLayout(jPanelCadastroOS);
        jPanelCadastroOS.setLayout(jPanelCadastroOSLayout);
        jPanelCadastroOSLayout.setHorizontalGroup(
            jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroOSLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroOSLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxResponsavelCadastroOS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroOSLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVeiculoCadatroOS)
                            .addComponent(jLabelDataEntradaCadastroOS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldDataEntradaCadastroOS)
                            .addComponent(jComboBoxVeiculoCadastroOS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroOSLayout.createSequentialGroup()
                        .addComponent(jButtonSalvarCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanelCadastroOSLayout.setVerticalGroup(
            jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroOSLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVeiculoCadatroOS)
                    .addComponent(jComboBoxVeiculoCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataEntradaCadastroOS)
                    .addComponent(jFormattedTextFieldDataEntradaCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxResponsavelCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanelCadastroOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarCadastroOS)
                    .addComponent(jButtonCancelarCadastroOS))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void prepararParaNovo() {
        presenter.prepararParaNovo(this);
    }

    private void jButtonSalvarCadastroOSActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by Presenter
    }

    private void jButtonCancelarCadastroOSActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by Presenter
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarCadastroOS;
    private javax.swing.JButton jButtonSalvarCadastroOS;
    private javax.swing.JComboBox<String> jComboBoxResponsavelCadastroOS;
    private javax.swing.JComboBox<String> jComboBoxVeiculoCadastroOS;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataEntradaCadastroOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDataEntradaCadastroOS;
    private javax.swing.JLabel jLabelVeiculoCadatroOS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastroOS;
    private javax.swing.JPanel jPanelDefeitoRelatadoCadastroOS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDefeitoRelatadoCadastroOS;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getButtonCancelarCadastroOS() { return jButtonCancelarCadastroOS; }
    public javax.swing.JButton getButtonSalvarCadastroOS() { return jButtonSalvarCadastroOS; }
    public javax.swing.JComboBox<String> getComboBoxVeiculoCadastroOS() { return jComboBoxVeiculoCadastroOS; }
    public javax.swing.JComboBox<String> getComboBoxResponsavelCadastroOS() { return jComboBoxResponsavelCadastroOS; }
    public javax.swing.JFormattedTextField getFormattedTextFieldDataEntradaCadastroOS() { return jFormattedTextFieldDataEntradaCadastroOS; }
    public javax.swing.JTextArea getTextAreaDefeitoRelatadoCadastroOS() { return jTextAreaDefeitoRelatadoCadastroOS; }
}
