/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.senai.fatesg.avcar.swing.views;

/**
 *
 * @author lucio-aguiar
 */
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;

import br.edu.senai.fatesg.avcar.swing.views.presenters.CadastroGarantiaPresenter;

@Component
public class CadastroGarantia extends javax.swing.JPanel {

    private final CadastroGarantiaPresenter presenter;

    @Autowired
    public CadastroGarantia(CadastroGarantiaPresenter presenter) {
        this.presenter = presenter;
        initComponents();
    }

    @jakarta.annotation.PostConstruct
    public void initLogic() {
        presenter.initLogic(this);
    }

    public void preparar(Long osId) {
        presenter.preparar(this, osId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelQdte = new javax.swing.JLabel();
        jTextFieldQdteValor = new javax.swing.JTextField();
        jButtonokqdtegrantia = new javax.swing.JButton();
        jButtonCancelarqtdegarantia = new javax.swing.JButton();

        jLabelQdte.setText("Quantidade de dias de Garantia");

        jButtonokqdtegrantia.setText("ok");

        jButtonCancelarqtdegarantia.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonokqdtegrantia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarqtdegarantia))
                    .addComponent(jLabelQdte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldQdteValor))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQdte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQdteValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonokqdtegrantia)
                    .addComponent(jButtonCancelarqtdegarantia))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarqtdegarantia;
    private javax.swing.JButton jButtonokqdtegrantia;
    private javax.swing.JLabel jLabelQdte;
    private javax.swing.JTextField jTextFieldQdteValor;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTextFieldQdteValor() { return jTextFieldQdteValor; }
    public javax.swing.JButton getButtonOk() { return jButtonokqdtegrantia; }
    public javax.swing.JButton getButtonCancelar() { return jButtonCancelarqtdegarantia; }
}
