package br.edu.senai.fatesg.avcar.swing.views;

import br.edu.senai.fatesg.avcar.business.servicos.ServicoController;
import br.edu.senai.fatesg.avcar.business.servicos.ServicoDTO;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import javax.swing.JOptionPane;

import br.edu.senai.fatesg.avcar.swing.views.presenters.CadastroServicoPresenter;

@Component
public class CadastroServico extends javax.swing.JPanel {

    @Autowired
    private CadastroServicoPresenter presenter;

    public CadastroServico() {
        initComponents();
    }
    
    @jakarta.annotation.PostConstruct
    public void initLogic() {
        presenter.initLogic(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroServico = new javax.swing.JPanel();
        jLabelNomeServico = new javax.swing.JLabel();
        jTextFieldNomeServico = new javax.swing.JTextField();
        jTextFieldDescricaoServico = new javax.swing.JTextField();
        jLabelDescricaoServico = new javax.swing.JLabel();
        jLabelValorServico = new javax.swing.JLabel();
        jLabelGarantiaServico = new javax.swing.JLabel();
        jLabelTempoEstimadoServico = new javax.swing.JLabel();
        jButtonSalvarServico = new javax.swing.JButton();
        jButtonCancelarServico = new javax.swing.JButton();
        jFormattedTextFieldValorServico = new javax.swing.JFormattedTextField();
        jFormattedTextFieldGarandiaServico = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTempoEstimadoServico = new javax.swing.JFormattedTextField();

        setToolTipText("Novo Cliente");

        jPanelCadastroServico.setToolTipText("Insira os Dados do novo Cliente");

        jLabelNomeServico.setText("Nome:");

        jLabelDescricaoServico.setText("Descrição:");

        jLabelValorServico.setText("Valor:");

        jLabelGarantiaServico.setText("Garantia (dias):");

        jLabelTempoEstimadoServico.setText("Tempo Estimado( Minutos):");

        jButtonSalvarServico.setText("Salvar");
        jButtonSalvarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarServicoActionPerformed(evt);
            }
        });

        jButtonCancelarServico.setText("Cancelar");
        jButtonCancelarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarServicoActionPerformed(evt);
            }
        });

        jFormattedTextFieldValorServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤¤#,##0.00"))));

        jFormattedTextFieldGarandiaServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextFieldTempoEstimadoServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanelCadastroServicoLayout = new javax.swing.GroupLayout(jPanelCadastroServico);
        jPanelCadastroServico.setLayout(jPanelCadastroServicoLayout);
        jPanelCadastroServicoLayout.setHorizontalGroup(
            jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroServicoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroServicoLayout.createSequentialGroup()
                        .addComponent(jButtonSalvarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeServico)
                            .addComponent(jLabelDescricaoServico)
                            .addComponent(jLabelValorServico)
                            .addComponent(jLabelGarantiaServico)
                            .addComponent(jLabelTempoEstimadoServico))
                        .addGap(25, 25, 25)
                        .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeServico)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroServicoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldDescricaoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldGarandiaServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldTempoEstimadoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        jPanelCadastroServicoLayout.setVerticalGroup(
            jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeServico)
                    .addComponent(jTextFieldNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescricaoServico)
                    .addComponent(jTextFieldDescricaoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorServico)
                    .addComponent(jFormattedTextFieldValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGarantiaServico)
                    .addComponent(jFormattedTextFieldGarandiaServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempoEstimadoServico)
                    .addComponent(jFormattedTextFieldTempoEstimadoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarServico)
                    .addComponent(jButtonCancelarServico))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarServicoActionPerformed
        presenter.salvarServico(this);
    }//GEN-LAST:event_jButtonSalvarServicoActionPerformed

    private void jButtonCancelarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarServicoActionPerformed
        presenter.cancelar(this);
    }//GEN-LAST:event_jButtonCancelarServicoActionPerformed

    public void preencherParaEdicao(Long id) {
        presenter.preencherParaEdicao(this, id);
    }

    public void prepararParaNovo() {
        presenter.prepararParaNovo(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarServico;
    private javax.swing.JButton jButtonSalvarServico;
    private javax.swing.JFormattedTextField jFormattedTextFieldGarandiaServico;
    private javax.swing.JFormattedTextField jFormattedTextFieldTempoEstimadoServico;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorServico;
    private javax.swing.JLabel jLabelDescricaoServico;
    private javax.swing.JLabel jLabelGarantiaServico;
    private javax.swing.JLabel jLabelNomeServico;
    private javax.swing.JLabel jLabelTempoEstimadoServico;
    private javax.swing.JLabel jLabelValorServico;
    private javax.swing.JPanel jPanelCadastroServico;
    private javax.swing.JTextField jTextFieldDescricaoServico;
    private javax.swing.JTextField jTextFieldNomeServico;
    // End of variables declaration//GEN-END:variables

    // Getters para os componentes
    public javax.swing.JTextField getTextFieldNomeServico() { return jTextFieldNomeServico; }
    public javax.swing.JTextField getTextFieldDescricaoServico() { return jTextFieldDescricaoServico; }
    public javax.swing.JFormattedTextField getFormattedTextFieldValorServico() { return jFormattedTextFieldValorServico; }
    public javax.swing.JFormattedTextField getFormattedTextFieldGarantiaServico() { return jFormattedTextFieldGarandiaServico; }
    public javax.swing.JFormattedTextField getFormattedTextFieldTempoEstimadoServico() { return jFormattedTextFieldTempoEstimadoServico; }
    public javax.swing.JButton getButtonSalvarServico() { return jButtonSalvarServico; }
    public javax.swing.JButton getButtonCancelarServico() { return jButtonCancelarServico; }
}
