/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.senai.fatesg.avcar.swing.views;

/**
 *
 * @author lucio-aguiar
 */
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import br.edu.senai.fatesg.avcar.swing.views.presenters.CadastroItemOSPresenter;

@Component
public class CadastroItemOS extends javax.swing.JPanel {

    private final CadastroItemOSPresenter presenter;

    @Autowired
    public CadastroItemOS(CadastroItemOSPresenter presenter) {
        this.presenter = presenter;
        initComponents();
    }

    @jakarta.annotation.PostConstruct
    public void initLogic() {
        presenter.initLogic(this);
    }

    public void preparar(Long osId) {
        presenter.preparar(this, osId);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneItensOS = new javax.swing.JTabbedPane();
        jPanelServicos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicos = new javax.swing.JTable();
        jButtonAdicionarItemServico = new javax.swing.JButton();
        jButtonRemoverItemServico = new javax.swing.JButton();
        jButtonFecharItenOS = new javax.swing.JButton();
        jPanelPecas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePecas = new javax.swing.JTable();
        jButtonAdicionarPeca = new javax.swing.JButton();
        jButtonRemoverPeca = new javax.swing.JButton();
        jButtonFecharPecas = new javax.swing.JButton();
        jPanelServExternos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableServExternos = new javax.swing.JTable();
        jButtonAdicionarServExternos = new javax.swing.JButton();
        jButtonRemoverServExternos = new javax.swing.JButton();
        jButtonFecharServExternos = new javax.swing.JButton();

        setName(""); // NOI18N

        jTableServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serviços", "Quantidade", "Valor Unitário", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableServicos);
        if (jTableServicos.getColumnModel().getColumnCount() > 0) {
            jTableServicos.getColumnModel().getColumn(1).setResizable(false);
            jTableServicos.getColumnModel().getColumn(2).setResizable(false);
            jTableServicos.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonAdicionarItemServico.setText("Adicionar");

        jButtonRemoverItemServico.setText("Remover");

        jButtonFecharItenOS.setText("Fechar");

        javax.swing.GroupLayout jPanelServicosLayout = new javax.swing.GroupLayout(jPanelServicos);
        jPanelServicos.setLayout(jPanelServicosLayout);
        jPanelServicosLayout.setHorizontalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
            .addGroup(jPanelServicosLayout.createSequentialGroup()
                .addComponent(jButtonAdicionarItemServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoverItemServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharItenOS))
        );
        jPanelServicosLayout.setVerticalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarItemServico)
                    .addComponent(jButtonRemoverItemServico)
                    .addComponent(jButtonFecharItenOS))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPaneItensOS.addTab("Serviços", jPanelServicos);

        jTablePecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Peça", "Quantidade", "Valor Unitário", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablePecas);
        if (jTablePecas.getColumnModel().getColumnCount() > 0) {
            jTablePecas.getColumnModel().getColumn(0).setResizable(false);
            jTablePecas.getColumnModel().getColumn(1).setResizable(false);
            jTablePecas.getColumnModel().getColumn(2).setResizable(false);
            jTablePecas.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonAdicionarPeca.setText("Adicionar");

        jButtonRemoverPeca.setText("Remover");

        jButtonFecharPecas.setText("Fechar");

        javax.swing.GroupLayout jPanelPecasLayout = new javax.swing.GroupLayout(jPanelPecas);
        jPanelPecas.setLayout(jPanelPecasLayout);
        jPanelPecasLayout.setHorizontalGroup(
            jPanelPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
            .addGroup(jPanelPecasLayout.createSequentialGroup()
                .addComponent(jButtonAdicionarPeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoverPeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharPecas))
        );
        jPanelPecasLayout.setVerticalGroup(
            jPanelPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPecasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPecasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarPeca)
                    .addComponent(jButtonRemoverPeca)
                    .addComponent(jButtonFecharPecas))
                .addContainerGap())
        );

        jTabbedPaneItensOS.addTab("Peças", jPanelPecas);

        jTableServExternos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fornecedor", "Descrição", "Valor", "Garantia (Dias)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableServExternos);
        if (jTableServExternos.getColumnModel().getColumnCount() > 0) {
            jTableServExternos.getColumnModel().getColumn(0).setResizable(false);
            jTableServExternos.getColumnModel().getColumn(1).setResizable(false);
            jTableServExternos.getColumnModel().getColumn(2).setResizable(false);
        }

        jButtonAdicionarServExternos.setText("Adicionar");

        jButtonRemoverServExternos.setText("Remover");

        jButtonFecharServExternos.setText("Fechar");

        javax.swing.GroupLayout jPanelServExternosLayout = new javax.swing.GroupLayout(jPanelServExternos);
        jPanelServExternos.setLayout(jPanelServExternosLayout);
        jPanelServExternosLayout.setHorizontalGroup(
            jPanelServExternosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
            .addGroup(jPanelServExternosLayout.createSequentialGroup()
                .addComponent(jButtonAdicionarServExternos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoverServExternos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharServExternos))
        );
        jPanelServExternosLayout.setVerticalGroup(
            jPanelServExternosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServExternosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServExternosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarServExternos)
                    .addComponent(jButtonRemoverServExternos)
                    .addComponent(jButtonFecharServExternos))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPaneItensOS.addTab("Serviços Externos", jPanelServExternos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneItensOS)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneItensOS, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarItemServico;
    private javax.swing.JButton jButtonAdicionarPeca;
    private javax.swing.JButton jButtonAdicionarServExternos;
    private javax.swing.JButton jButtonFecharItenOS;
    private javax.swing.JButton jButtonFecharPecas;
    private javax.swing.JButton jButtonFecharServExternos;
    private javax.swing.JButton jButtonRemoverItemServico;
    private javax.swing.JButton jButtonRemoverPeca;
    private javax.swing.JButton jButtonRemoverServExternos;
    private javax.swing.JPanel jPanelPecas;
    private javax.swing.JPanel jPanelServExternos;
    private javax.swing.JPanel jPanelServicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneItensOS;
    private javax.swing.JTable jTablePecas;
    private javax.swing.JTable jTableServExternos;
    private javax.swing.JTable jTableServicos;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getButtonAdicionarItemServico() { return jButtonAdicionarItemServico; }
    public javax.swing.JButton getButtonAdicionarPeca() { return jButtonAdicionarPeca; }
    public javax.swing.JButton getButtonAdicionarServExternos() { return jButtonAdicionarServExternos; }
    public javax.swing.JButton getButtonFecharItenOS() { return jButtonFecharItenOS; }
    public javax.swing.JButton getButtonFecharPecas() { return jButtonFecharPecas; }
    public javax.swing.JButton getButtonFecharServExternos() { return jButtonFecharServExternos; }
    public javax.swing.JButton getButtonRemoverItemServico() { return jButtonRemoverItemServico; }
    public javax.swing.JButton getButtonRemoverPeca() { return jButtonRemoverPeca; }
    public javax.swing.JButton getButtonRemoverServExternos() { return jButtonRemoverServExternos; }
    public javax.swing.JTable getTablePecas() { return jTablePecas; }
    public javax.swing.JTable getTableServExternos() { return jTableServExternos; }
    public javax.swing.JTable getTableServicos() { return jTableServicos; }
}
