/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.senai.fatesg.avcar.swing.views;

/**
 *
 * @author lucio-aguiar
 */
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;

import br.edu.senai.fatesg.avcar.swing.views.presenters.CadastroDescontoPresenter;

@Component
public class CadastroDesconto extends javax.swing.JPanel {

    private final CadastroDescontoPresenter presenter;

    @Autowired
    public CadastroDesconto(CadastroDescontoPresenter presenter) {
        this.presenter = presenter;
        initComponents();
    }

    @jakarta.annotation.PostConstruct
    public void initLogic() {
        presenter.initLogic(this);
    }

    public void preparar(Long osId) {
        presenter.preparar(this, osId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAplicarDesconto = new javax.swing.JLabel();
        jTextFieldAplicarDesconto = new javax.swing.JTextField();
        jButtonokAplicarDesconto = new javax.swing.JButton();
        jButtonCancelarAplicarDesconto = new javax.swing.JButton();

        jLabelAplicarDesconto.setText("Aplicar Desconto");

        jButtonokAplicarDesconto.setText("ok");

        jButtonCancelarAplicarDesconto.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAplicarDesconto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonokAplicarDesconto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCancelarAplicarDesconto))
                        .addComponent(jTextFieldAplicarDesconto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelAplicarDesconto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAplicarDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonokAplicarDesconto)
                    .addComponent(jButtonCancelarAplicarDesconto))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarAplicarDesconto;
    private javax.swing.JButton jButtonokAplicarDesconto;
    private javax.swing.JLabel jLabelAplicarDesconto;
    private javax.swing.JTextField jTextFieldAplicarDesconto;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTextFieldAplicarDesconto() { return jTextFieldAplicarDesconto; }
    public javax.swing.JButton getButtonOk() { return jButtonokAplicarDesconto; }
    public javax.swing.JButton getButtonCancelar() { return jButtonCancelarAplicarDesconto; }
}
